from src.config.config import ROOT_FOLDER_PATH, Path, load_config

LOG_FOLDER_PATH: Path = ROOT_FOLDER_PATH / "logs"

CONFIG: dict[str, str | None] = load_config()

DEFAULT_ENV: str = "dev"

ENV: str = CONFIG.get("ENV") or DEFAULT_ENV

IS_PROD: bool = ENV == "prod"

TEAMS_WORKFLOW_CONFIG: dict[str, str | None] = {
    "url": CONFIG.get("TEAMS_WORKFLOW_URL"),
    "title": ROOT_FOLDER_PATH.name,
}

DEFAULT_QRADAR_SEARCH_QUERY_INTERVAL: int = 15

DEFAULT_QRADAR_MAX_SEARCH_QUERY_INTERVAL: int = 1440
QRADAR_MAX_SEARCH_QUERY_INTERVAL: int = int(
    CONFIG.get("QRADAR_MAX_SEARCH_QUERY_INTERVAL")
    or DEFAULT_QRADAR_MAX_SEARCH_QUERY_INTERVAL
)

DEFAULT_QRADAR_SEARCH_QUERY_LIMIT: int = 9999

DEFAULT_QRADAR_SEARCH_QUERY_COMPLETED_REQUEST_ATTEMPTS: int = 15
QRADAR_SEARCH_QUERY_COMPLETED_REQUEST_ATTEMPTS: int = int(
    CONFIG.get("QRADAR_SEARCH_QUERY_COMPLETED_REQUEST_ATTEMPTS")
    or DEFAULT_QRADAR_SEARCH_QUERY_COMPLETED_REQUEST_ATTEMPTS
)

DEFAULT_QRADAR_SEARCH_QUERY_COMPLETED_REQUEST_DELAY: int = 1
QRADAR_SEARCH_QUERY_COMPLETED_REQUEST_DELAY: int = int(
    CONFIG.get("QRADAR_SEARCH_QUERY_COMPLETED_REQUEST_DELAY")
    or DEFAULT_QRADAR_SEARCH_QUERY_COMPLETED_REQUEST_DELAY
)
